services:
  - type: web
    name: alpharaceteam-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: PORT
        value: "3000"
    healthCheckPath: /health
    autoDeploy: true
    plan: free

  - type: cron
    name: email-processor
    env: node
    buildCommand: npm install
    startCommand: node src/workers/emailWorker.js start
    envVars:
      - key: NODE_ENV
        value: production
      - key: RESEND_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
    schedule: "*/5 * * * *"  # A cada 5 minutos
    plan: free 